name = "car-spa-crm"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kl01-alok-db"
database_id = "5c1361fb-afb4-4b6b-9bf2-576d1beb451a"
migrations_dir = "drizzle"

