name = "kl01-alok"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "car-spa-db"
database_id = "9558c3e9-524c-41c0-a2e6-2a1bc060b783"