name = "car-spa-crm"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "car-spa-db"
database_id = "140df486-e642-404a-b5bc-b6e65e5324f4"